### ISSUE TITLE
Get tags (releases) and changelogs up to date

### ISSUE THREAD

**Issue by wikimatze** [ryanoasis/vim-webdevicons#17]
The last one is over one year old.

**Comment by ryanoasis** [comment]
I'm sorry? Not sure I follow what you are referring to

**Comment by wikimatze** [comment]
I'm using a plugin manager for vim called [vim-plug](https://github.com/junegunn/vim-plug) and I don't always want to grab from master to track the changes a plugin takes.

**Comment by ryanoasis** [comment]
Okay I see. I'm still pleading ignorance though because I am still not understanding. What is this ticket for exactly? Thanks

**Comment by wikimatze** [comment]
To make you up to create a tag which I can take for my plugin manager so that I know which version I'm using.

**Comment by ryanoasis** [comment]
thanks. ah okay I see what you mean now. Sorry.

I am behind on the release versioning and tags

the latest one is **24 Nov 2014 v0.1.3**

it's not over one year old but it is from last calendar year. there have been a few releases since then obviously I just haven't gotten around to bumping, updating changeset and pushing new tags. I plan to do this however and I will make sure to update this ticket :smile:

**Comment by wikimatze** [comment]
Juhu :+1:

**Comment by ryanoasis** [comment]
tags have been pushed and changelog updated

**Comment by wikimatze** [comment]
Juhu!
