### ISSUE TITLE
support gnome terminal

### ISSUE THREAD

**Issue by calidion** [ryanoasis/vim-webdevicons#21]
how to?

**Comment by ryanoasis** [comment]
@calidion I am not sure I know what you are asking. How to use this in non-GUI Vim and in the terminal?

**Comment by calidion** [comment]
yes.

**Comment by calidion** [comment]
vim-airline works with terminal or shell environment.

**Comment by ryanoasis** [comment]
@calidion which terminal do you use? konsole? rxvt? gnome? xfce? other?

And did you set the font to one of the patched fonts for your terminal?

**Comment by calidion** [comment]
gnome,  but the font will not show in the term's font list.

**Comment by ryanoasis** [comment]
I am assuming you installed one of the fonts, per: https://github.com/ryanoasis/vim-webdevicons#font-installation ?

**Comment by ryanoasis** [comment]
@calidion thank you for this because this **does** in fact look like an issue with the fonts. I have tried gnome-terminal on my system and I cannot see any of the patched fonts to show up in the preferences.

Making this work across more terminals is probably going to be the next big thing I try to fix.

For reference what I did try but did **not** work for me:
`fc-list | grep "Nerd File Types"`
http://www.linuxquestions.org/questions/linux-software-2/fonts-not-listed-in-gnome-terminal-preferences-4175446941/

**Comment by ryanoasis** [comment]
WIP: https://cloud.githubusercontent.com/assets/8083459/6205330/63451b90-b538-11e4-9b5e-11f4d5c3afc8.png

**Comment by ryanoasis** [comment]
For reference and linking ryanoasis/nerd-filetype-glyphs-fonts-patcher#4

**Comment by ryanoasis** [comment]
working now as of:
* ryanoasis/nerd-filetype-glyphs-fonts-patcher@6c6ef8ef0ca382efbd39bd709007e6ee8f64edbf
 * with mono spaced cli flag
  * e.g. `./font-patcher unpatched-sample-fonts/Droid\ Sans\ Mono\ for\ Powerline.otf --use-single-width-glyphs --quiet`
