### ISSUE TITLE
Icons not showing in vim under urxvt

### ISSUE THREAD

**Issue by valir** [ryanoasis/vim-webdevicons#36]
Using urxvt-256color and vim on archlinux.

Font setting in ~/.Xresources
URxvt.font: xft:Droid Sans Mono for Powerline Plus Nerd File Types:size=11
URxvt.boldFont: xft:Droid Sans Mono for Powerline Plus Nerd File Types:bold:size=11

I downloaded your patched font under ~/.fonts
xset q confirms ~/.fonts is searched

:echo g:WebDevIconsUnicodeDecorateFileNodesDefaultSymbol 
displays a small rectangle, the same I see in NERDTree instead of the icons

If I launch gvim, it works. The problem is only present in vim.

**Comment by ryanoasis** [comment]
@valir it looks to me like you are not using the _"mono"_ versionof Droid Sans (which is needed to work in urxvt). The one you want has "mono" in the name twice :stuck_out_tongue: : 

`Droid Sans Mono for Powerline Plus Nerd File Types Mono`
instead of
~~`Droid Sans Mono for Powerline Plus Nerd File Types`~~

Sorry for the confusion, naming pattern could probably use some improvement.

Here is what I have for my settings:
`URxvt*font: xft:Droid Sans Mono for Powerline Plus Nerd File Types Mono:pixelsize=16:antialias=true:hinting=true`

**Comment by valir** [comment]
Right, using the Mono version fixes the issue. Thanks!
