### ISSUE TITLE
Gvim nerdtree redraw on folder open

### ISSUE THREAD

**Issue by kristijanhusak** [ryanoasis/vim-webdevicons#58]
Hi,

I have a bug, that probably can not be fixed, or it's not related to this plugin, but i'll post it here because i noticed it when i installed this. When i open nerdtree, icons are there, but when i open subfolder, beside icon for filetype, i get strange overlaps with other icons:

![nerdtree-webdevicons-bug](https://cloud.githubusercontent.com/assets/1782860/8006611/da174096-0b95-11e5-8580-553b37f959f0.png)

As soon as i select a file, that overlaping dissapears and everything looks fine. It's not a much of a deal, but can be annoying. It happens **only in Gvim**, in terminal vim works fine. I tried calling `:redraw` but it didn't work out.

I believe it's some of the VIM redrawing issues, but not sure.

Here are some details about the system if needed:
OS: Xubuntu 15.04 x64
Vim: VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun  5 2015 15:51:32)
Included patches: 1-729
Vimrc: https://github.com/kristijanhusak/vimfiles/blob/master/vimrc

**Comment by ryanoasis** [comment]
@kristijanhusak Sorry and thanks I will try to replicate it. What patched font are you using btw ?

**Comment by kristijanhusak** [comment]
@ryanoasis i'm using inconsolata, downloaded it from that repo with already patched fonts.
Thanks. Great plugin btw, it really modernizes the vim :-)

**Comment by alxdnlnko** [comment]
+1, got the same artifacts
when open subfolder
![](http://rb14.reliablehosting.com/screens/2015-06-08--1433732694_159x182_scrot.png)

when close nerd-tree
![](http://rb14.reliablehosting.com/screens/2015-06-08--1433732806_98x214_scrot.png)

**Comment by ryanoasis** [comment]
@alxdnlnko Does this only occur in gvim and not vim for you as well?

**Comment by alxdnlnko** [comment]
@ryanoasis only in Gvim

**Comment by ryanoasis** [comment]
@alxdnlnko , @kristijanhusak 

1. can you see if the artifacts go away with:
```vim
:redraw!
```
2. can you see if the artifacts stop appearing with the following set in your vimrc:
```vim
let g:webdevicons_conceal_nerdtree_brackets = 0
```

I **was** able to replicate this issue after all, so far at least it seems to be the combination of gvim and conceal. There is probably more to it but it seems like a `redraw` call on NERDTree refresh when in gvim might be a solution. I will work and test on that theory

**Comment by alxdnlnko** [comment]
@ryanoasis 
1. yes, `:redraw!` helps
2. `let g:webdevicons_conceal_nerdtree_brackets = 0` it doesn't help, when you open more than one levels at once:
http://rb14.reliablehosting.com/screens/2015-06-09--1433808978_173x573_scrot.png

The problem is that nerd-tree doesn't redraw the whole line. Maybe you should add a `:redraw!` as a stopgap measure, and create an issue in nerd-tree?

**Comment by kristijanhusak** [comment]
@ryanoasis 
Confirming that `:redraw` works, and `let g:webdevicons_conceal_nerdtree_brackets = 0` not working.

**Comment by ryanoasis** [comment]
@kristijanhusak , @alxdnlnko 

I had a hard time auto executing `:redraw!` at a point where it would help (hard to detect directory open/close) and also it seemed like it would be a bit slow.

However after even more testing I discovered there is some problem with the **glyphs** themselves. E.g. if you changed all the default mappings in your `vimrc` to say 'A' or something the problem goes away. What I tried was messing around with fontforge and the patcher script for several hours and confirmed I could get the issue to go away with how the glyphs are resized when importing.

In conclusion a proper fix would be to fix the glyph issues but for me it is not going to be easy as I am nowhere near a fontforge expert.

**TEMP SOLUTION: BUT I do think I have found a not terrible hack to fix the issue :smile:**

What I did was add a second filler character to the end of the glyph returned and it seems to solve the rendering issues, in the `WebDevIconsGetFileTypeSymbol` method change the return

**from:**
```vim
return symbol
```

**to:**
```vim
return symbol . "\u00A0"
```

**gvim after fix AND gvim before fix:**
![selection_11_06_15_13 28 34_511x439_001](https://cloud.githubusercontent.com/assets/8083459/8114028/d46f80d2-103f-11e5-828d-2839fb993171.png)


_NOTE: the issue is ***not*** limited to NERDTree, as you can see in airline after I scolled to the bottom of a large file (`<S-g>`)_

Any character that has content except space actually seems to work here. I don't see any side effect so far

Wow this one really threw me down the rabbit hole.

If this works for you **please** let me know and if so I am going to do more testing and push a fix

**Comment by kristijanhusak** [comment]
@ryanoasis 
I tested it out. It is **much** better! It's working almost perfect. I just noticed when going up from child folder to parent with `u`, some icons are overlapped with some character, not sure if it's same for all.
(Go to folder with `C`, and then go back with `u`).

Here's the version **with overlapped character**:
![with-overlapped-char](https://cloud.githubusercontent.com/assets/1782860/8116799/714ecbb2-1084-11e5-9412-2e38e2b0d21d.png)

And this is after `:redraw!` (Normal):
![after-redraw](https://cloud.githubusercontent.com/assets/1782860/8116807/806d4eac-1084-11e5-9d77-ff30db2cda73.png)

It's really strange, sometimes it's for 1 icon, sometimes none, sometimes several.

Anyway, I approve this as a fix, because it's barely noticable.

**Comment by ryanoasis** [comment]
@kristijanhusak 
Hmm I was going to ask you for a screencast of the issue but I **just** replicated it but in a different way. For me it was just `C` on a folder with all files and no sub-directories. 

Seems like `o` works fine but changing the current directory and making it the new root `C` is causing problems.

![screencast_11-jun-2015-05 04 38](https://cloud.githubusercontent.com/assets/8083459/8118311/1fb4b03c-105c-11e5-92bd-75e612412b5c.gif)

**Comment by kristijanhusak** [comment]
Yes, `o` works fine for me also, only root changing causes the problem.
If you can add the fix, it's much better anyway, because icons are not overlapping on sides.

**Comment by ryanoasis** [comment]
@kristijanhusak, Yep it is an improvement at least like you said. I think what I will do is push up the improvement but leave this open at least make some small attempts to fix the other scenarios

**Comment by kristijanhusak** [comment]
@ryanoasis Ok, great! Thanks!

**Comment by ryanoasis** [comment]
@kristijanhusak, @alxdnlnko This is pretty much done and fixed just want to do a bit more testing before releasing. 

Even the key mappings with the issues *should* work

If either of you would like to check this out: [branch 0.4.3](https://github.com/ryanoasis/vim-webdevicons/tree/0.4.3)

**Comment by kristijanhusak** [comment]
@ryanoasis 

This problem is solved with this, but some other appeared. Screen is redrawing on every move (horizontal, vertical) when NERDTree is closed, which causes flickering. Would not recommend leaving that behavior.

Also, spacing between icons and text in nerdtree is a bit too big for my taste:
![icons-spacing](https://cloud.githubusercontent.com/assets/1782860/8138891/5dd18cfc-114f-11e5-808f-2a4c3d27991e.png)

Probably can be modified with global variable.

**Comment by ryanoasis** [comment]
@kristijanhusak I didn't notice any flickering but I will look more closely thanks!

For the spacing you can adjust that:
```vim
let g:WebDevIconsNerdTreeAfterGlyphPadding = '  '
```

I think a separate fix I adjusted the default yet again (because of the conceallevel)

**Comment by kristijanhusak** [comment]
@ryanoasis 
Here's the short gif. Not the best quality, but I think it is visible enough.
![ezgif com-resize](https://cloud.githubusercontent.com/assets/1782860/8139461/3f390388-1154-11e5-887a-e77a46b1faef.gif)

**Comment by ryanoasis** [comment]
@kristijanhusak Great thanks for the gif, yeah that is **really** bad. Hopefully I can track down the `redraw!` that I added which is causing this. Might be the one for the filetype glyph in the statusline but we'll see
